apiVersion: v1
kind: Service
metadata:
  namespace: anotherclass-223
  name: api-tester-2231
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2231
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2231
  ports:
    - port: 80
      targetPort: http
      nodePort: 32231
  type: NodePort
