
image:
  repository: 1pro/api-tester
  pullPolicy: Always
  tag: "v2.0.0"

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

service:
  nodePort: 32222

configmap:
  data:
    properties:
      spring_profiles_active: "dev"
      application_role: "ALL"
      postgresql_filepath: "/usr/src/myapp/datasource/postgresql-info.yaml"

secret:
  data:
    postgresql:
      postgresql-info.yaml: |
        driver-class-name: "org.postgresql.Driver"
        url: "jdbc:postgresql://postgresql:5431"
        username: "dev"
        password: "dev123"