
replicaCount: 1

image:
  repository: 1pro/api-tester
  pullPolicy: Always
  tag: 1.0.0

resources:
  limits:
    cpu: 210m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

configmap:
  data:
    properties:
      spring_profiles_active: "dev"
      application_role: "ALL"
      postgresql_filepath: "/usr/src/myapp/datasource/postgresql-info.yaml"

secret:
  data:
    postgresql:
      postgresql-info.yaml: |
        driver-class-name: "org.postgresql.Driver"
        url: "jdbc:postgresql://postgresql:5431"
        username: "dev"
        password: "dev123"