apiVersion: v1
kind: Service
metadata:
  name: api-tester-2233-preview
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2233
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2233
  ports:
    - port: 80
      targetPort: http
      nodePort: 32243
  type: NodePort
